### ISSUE TITLE
Tabbed module not working

### ISSUE THREAD

**Issue by carcam** [JEvents/JEvents#216]
Tabbed module is not working anymore with jQuery version as the module is trying to load the class _moduletabs_ that is not defined.
![moduletabsnotdefined](https://cloud.githubusercontent.com/assets/1695138/3941413/a3ec5678-2527-11e4-996b-b3d078410142.png)
### How to reproduce
1. Add the tabbed module with a couple of tabs

**Comment by tonypartridge** [comment]
I think this is quite a rare scenario? Closing as nothing has been actioned.
