### ISSUE TITLE
Incorrect access behaviour

### ISSUE THREAD

**Issue by mgi** [JEvents/JEvents#242]
I'm using JEvents 3.1.30 on Joomla! 2.5.27 and have trouble setting access from groups right.
Example:
A user U is in group A and B. In a JEvents category, group A can't create event and group B can create event then user U won't be able to create an event of this category (i.e. the group with least rights wins: this is exactly the other way around with Joomla! articles).

**Comment by tonypartridge** [comment]
This was now 2 years ago, so closing. Please re-open if you have any comments.
