### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by cescalante** [JEvents/JEvents#252]
This might be a total coincidence or it could be a targeting of a commonly installed plugin but we run an install base of about 80 Joomla sites with several of them running jEvents. We have found over the last weeks NUMEROUS hacking attempts with a common element always being the manipulation of /public_html/administrator/manifests/packages/jevents/install.php. Now, they always hit other things and I want you to understand we are very early in to figuring this out but jEvents is one of the common elements across the sites hacked. Are you aware of any security related incidents elsewhere pertaining to that file?

**Comment by xtech86** [comment]
Hello,

Thank you for raising an issue. 

There are no known issues that we are aware off. 

I have checked the file location you have mentioned and it is just the package install script. All of which uses official Joomla! classifications, so for any injection attempts etc they are all filtered out via the Joomla! filtering mechanisms.

There is no issues of which I can see occurring from this.

Thanks
Tony

**Comment by GeraintEdwards** [comment]
This file contains a single self contained class and will always immediately exit with the message 'Restricted access' if run.

I suspect its the name of the file that is causing the temptation to have a go.
