### ISSUE TITLE
Do not show popup link for menu item if no popup plugin

### ISSUE THREAD

**Issue by carcam** [JEvents/JEvents#265]
I think we should detect the popup plugin is not installed and offer the full url to the menu item of creating evetns. Otherwise it looks  a bit buggy.

https://www.jevents.net/forum/viewtopic.php?f=35&t=28079

**Comment by xtech86** [comment]
I think we should remove the option from JEvents completely and then add it to the event details popup and allow a selection of which can be used.

**Comment by carcam** [comment]
That might arise some issues on existing sites, so although I like the idea, we need to take that into consideration too.

**Comment by GeraintEdwards** [comment]
It all going to need to be refactored for jQuery/Bootstrap modals in any 
case.
