### ISSUE TITLE
Add Display none by default to modal edit windows

### ISSUE THREAD

**Issue by tonypartridge** [JEvents/JEvents#310]
For the ical action and the edit action dialog modals we need to set a display none by default, otherwise in certain views the links override the other modals links and so on. Setting a display:none; makes them hidden unless specified otherwise.

**Comment by GeraintEdwards** [comment]
Can you make a PR for this and also give a little more explanation.  The 
JEvents css files should be hiding the modals - are you saying that 
isn't enough for some sites?

**Comment by xtech86** [comment]
It is hiding it Geraint, but not quite. So we need to apply a display none. I'll try and do it monday so you can see it.
