### ISSUE TITLE
install on postgresql database

### ISSUE THREAD

**Issue by jdeproost** [JEvents/JEvents#33]
To install on:
PHP Built On    Windows NT 2JFVL4J-LI 6.1 build 7600 (Windows 7 Business Edition) i586
Database Version    9.2.2
Database Collation  Dutch_Netherlands.1252
PHP Version     5.4.7
Web Server  Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7
WebServer to PHP Interface  apache2handler
Joomla! Version     Joomla! 3.0.3 Stable [ Ember ] 04-February-2013 14:00 GMT
Joomla! Platform Version    Joomla Platform 12.2.0 Stable [ Neil Armstrong ] 21-September-2012 00:00 GMT
User Agent  Mozilla/5.0 (Windows NT 6.1; rv:19.0) Gecko/20100101 Firefox/19.0 

I had to rewrite the vevent table creation as this:

CREATE TABLE IF NOT EXISTS k29if_jevents_vevent(ev_id serial NOT NULL,icsid int NOT NULL default 0,catid int NOT NULL default 1,uid varchar(255) NOT NULL UNIQUE default '',refreshed datetime NOT NULL default '0001-01-01 00:00:00',created datetime NOT NULL default '0001-01-01 00:00:00',created_by int NOT NULL default '0',created_by_alias varchar(100) NOT NULL default '',modified_by int NOT NULL default '0',rawdata longtext NOT NULL default '',recurrence_id varchar(30) NOT NULL default '',detail_id int NOT NULL default 0,state tinyint NOT NULL default 1,lockevent tinyint NOT NULL default 0,author_notified tinyint NOT NULL default 0,access int NOT NULL default 0,PRIMARY KEY (ev_id))

**Comment by chgerwig** [comment]
Hi, 
I just got a similar error on Joomla 3.4.8 with postgresql.
Since nearly 3 years are over from the last post is the status still the same?
