### ISSUE TITLE
uikit: Club Theme Options tab missing from JEvents configuration

### ISSUE THREAD

**Issue by skurvish** [JEvents/JEvents#466]
As stated, there is no tab in the JEvents configuration for club layouts.

**Comment by GeraintEdwards** [comment]
I see the tab ok - do you have any installed?

**Comment by skurvish** [comment]
I have ruthin installed and that is my default. I installed the uikit build over top of a production clone. No Club Theme tab.

**Comment by skurvish** [comment]
Caused by themes not installed in the repo after symlink.
