### ISSUE TITLE
uikit: club theme is lost on installation

### ISSUE THREAD

**Issue by skurvish** [JEvents/JEvents#467]
When installing the uikit version on top of an existing installation we lose the club theme. I am using Ruthin but when I installed the new JEvents the theme was changed to alternate and the Ruthin theme is no longer in the dropdown list.

**Comment by GeraintEdwards** [comment]
I didn't see this happen - did you install on top of a symbolically linked setup?

**Comment by skurvish** [comment]
No, I cloned the site using akeeba, then installed both JEvents and RSVP uikit packages, then I ran the sym link process.

**Comment by skurvish** [comment]
Turns out this was due to doing a sym link to the repo which did not have the theme installed.
