### ISSUE TITLE
uikit: yes/no booleans incorrect in configuration

### ISSUE THREAD

**Issue by skurvish** [JEvents/JEvents#468]
Most of the yes/no options in the JEvents configuration are not being displayed as such. They are being displayed as a text field with the value of 0 or 1 in it. Looking at the html it seems they are being rendered as type="text" rather than type="radio" with options.

**Comment by GeraintEdwards** [comment]
They work fine for me - can you give me a specific example of one that doesn't work and also the source HTML for the elements concerned.

Mine look like this

<fieldset id="jform_darktemplate" class="gsl-button-group gsl-button-group">

						
						<input type="radio" id="jform_darktemplate0" name="jform[darktemplate]" value="0" checked="checked" class="gsl-button-small gsl-radio gsl-hidden">			<label for="jform_darktemplate0" class="gsl-button-small gsl-button  gsl-button-danger">
				No			</label>
					
						<input type="radio" id="jform_darktemplate1" name="jform[darktemplate]" value="1" class="gsl-button-small gsl-radio gsl-hidden">			<label for="jform_darktemplate1" class="gsl-button-small gsl-button gsl-button-default">
				Yes			</label>
			</fieldset>

![Screenshot_2020-03-26 JEvents Configuration - Joomla 30 Production - Administration](https://user-images.githubusercontent.com/839810/77648299-d25b5a80-6f5f-11ea-8cb3-c2ce47550ff2.png)

**Comment by skurvish** [comment]
Same control, mine looks like this:
`<span class="editlinktip"><label id="jform_darktemplate-lbl" for="jform_darktemplate" class="hasPopover" title="" data-content="If your site uses a template with a dark background please try setting this config option to true" data-original-title="Site template has dark background">
	Site template has dark background</label>
</span>`

**Comment by skurvish** [comment]
Working in current release.
