### ISSUE TITLE
Stablish Adding repeat permission

### ISSUE THREAD

**Issue by carcam** [JEvents/JEvents#76]
Makes the "repeats permission" an option into our permissions group so that usersd do not have to be editors to submit an event with repeats:
http://www.jevents.net/forum/viewtopic.php?f=24&t=20762&p=108002#p108001

**Comment by tonypartridge** [comment]
I've looked into this, by default it would be disabled which would be a B/C break. It would require us to write a permissions helper on install to check the current groups etc and then add the new access level in. since it has been 3 years since this and no other requests, I'm closing it.
